### PR TITLE
Replace Jira information in the location it originally appeared in the pull request description

### PR DESCRIPTION
**Pull request by millerick**
My company uses this action and other similar actions to automatically place information in pull request bodies.  This action is currently limiting in that it requires the computer generated information to be placed at the beginning of the pull request description.  Many of our repository owners want their pull request descriptions to follow this format:
* human generated content at the top of the pull request description
* computer generated and maintained content below it

Currently this is not possible since this action always puts the information at the top of the pull request description, which has the effect of sandwiching human generated content between computer generated content.

These changes will allow repository owners to include in the location they want in their pull request template and have the action replace the information in that specific location.
```
<!--jira-description-action-hidden-marker-start-->

<!--jira-description-action-hidden-marker-end-->
```

### CODE REVIEW

**Comment by cakeinpanic** [comment]
Hi, thank you for your PR!
I understand the idea, but what would you say if we just add an additional input for this action, like `injectLabel: 'below' | 'above'`?
Would it solve your issue?

**Comment by millerick** [comment]
> Hi, thank you for your PR! I understand the idea, but what would you say if we just add an additional input for this action, like `injectLabel: 'below' | 'above'`? Would it solve your issue?

I don't think that would be a bad option to have for the action, but it also doesn't solve my issue.  It does not address when there are multiple actions that put automated information into the description.  Even if all of them are trying to put the information at the bottom of the description, the order of those items will not be deterministic.  I.e. even if the Jira information runs and completes before an action that adds code coverage information to the description, I may still want to have the code coverage information display above the Jira information.  Overall, I think it is beneficial to be able to control exact placement.

**Review by cakeinpanic — APPROVED** [review]
LGTM, let's merge it!

I'd slightly change the README after merge and before releasing tho :)

**Comment by millerick** [comment]
> I'd slightly change the README after merge and before releasing tho :)

Feel free to, or let me know what changes you would like and I can make them as well.

**Pull request merged**
