### PR TITLE
Remove unused dependencies

### PR DESCRIPTION
**Pull request by javierjulio**
As promised from #49 this is a follow up to remove unused dependencies as I noticed some while working on that PR.

I tried addressing some security updates but any seem to break CI, although running tests locally is successful. Addressing the many outdated dependencies should be done individually. I won't be able to contribute there as I'm not familiar with Typescript and Jest which have the most.

### CODE REVIEW

**Comment by javierjulio** [comment]
@cakeinpanic as mentioned in #49 this is a follow up to help reduce the number of dependencies and those reduce the lock file size. CI is green with this change and tests pass locally as well.

**Review by kevnm67 — APPROVED** [review]
LGTM ✋

**Comment by cakeinpanic** [comment]
Hi, I don't see the reason to remove `engines-ok` dependency since on my laptop which has node18 installed globally it actually _did_ prevent the build. Please bring it back or provide another solution which would do the same job

**Comment by javierjulio** [comment]
@cakeinpanic no worries, I dropped that commit so it remains in place. This is now ready.

**Review by cakeinpanic — APPROVED** [review]

**Pull request merged**
