### PR TITLE
feat: ✨ fetch body from context

### PR DESCRIPTION
**Pull request by cchanche**

### CODE REVIEW

**Comment by cchanche** [comment]
Opening here was a mistake from me wanting to edit locally for our company.

**Comment by cakeinpanic** [comment]
@cchanche Hi, fetching body from API was added on purpose https://github.com/cakeinpanic/jira-description-action/pull/30
It's needed to be able to run multiple steps of changing PR body within one workflow

If you want to fecth it form context, please use previous version of this action: [0.3.2](https://github.com/cakeinpanic/jira-description-action/releases/tag/v0.3.2)

**Comment by cchanche** [comment]
Hey @cakeinpanic, thank you for your reply. 

In my workflow, I have multiple steps editing the PR body, and all of them use the github context. Using this action in a step among those other ones, causes the PR body to reset to the state it was before the workflow started.
I strongly believe it is because GithubAction waits until a workflow is finished to write the new body (when using context), and _jira-description-action_, by reading the body from the API, won't work with the most recent body (which is, for me, located in the context).

> It's needed to be able to run multiple steps of changing PR body within one workflow

Considering my hypothesis, I suppose this should be rephrased _"...multiple steps of changing PR body **with an API call** within one workflow._

Be aware that I did not tested any of this yet, and that I am neither familiar with the `@action/toolkit` and `@action/github` libraries, nor with writing custom javascript actions.

Also thank you for pointing me to version [0.3.2](https://github.com/cakeinpanic/jira-description-action/releases/tag/v0.3.2), I see how I didn't think of using the dedicated `getGithubData()` method to access context.

**Comment by cakeinpanic** [comment]
@cchanche can you tell me which other actions you using or better share the whole workflow file?
 Because the reason to fetch PR body was exactly because I was using other actions and they were fetching PR body from context _not_ respecting changes made by other actions. 
long story short this fetch from API was fishing your exact pain 

the only thing you should do – place this action as the **last** step of the workflow. So it’d fetch the most recent state

**Comment by cchanche** [comment]
Using context instead of API, I ended up having the exact same problem. Since you already went over this problem I decided to refactor the action to output the jira-description instead of updating the body, and leave the body-update for a single job.

I sadly don't have a lot of time for this right now, but I'll keep looking into it once I do. I would love to have a proper solution and maybe even contribute here if you feel like it could be useful.

For now, here is the workflow-file I tested the action with, using context **and** the API.

```yml
name: Set PR description
on:
  pull_request:
    types: [opened, synchronize, edited, reopened, ready_for_review]

jobs:

  tag-version:
    name: 🏷️ Create tag version
    runs-on: ubuntu-20.04
    outputs:
      new-tag: ${{ steps.tag_version.outputs.new-tag }}
      previous-tag: ${{ steps.tag_version.outputs.previous-tag }}
      new-version: ${{ steps.tag_version.outputs.new-version }}
      new-tag-raw: ${{ steps.tag_version.outputs.new-tag-raw }}
      new-version-raw: ${{ steps.tag_version.outputs.new-version-raw }}
      run-id: ${{ steps.tag_version.outputs.run-id }}
      changelog: ${{ steps.tag_version.outputs.changelog }}
    steps:
      - name: ✔️ Checkout repo
        uses: actions/checkout@v3

      - uses: ./.github/actions/tag-version
        id: tag_version
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  upsert-pr-body:
    name: 💬 Release details
    runs-on: ubuntu-20.04
    needs:
      [
        tag-version,
      ]
    steps:

      - name: ✔️ Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Output commit message
        id: cm
        run: echo "message=$(git log -1 --pretty=format:\"%s\")" >> $GITHUB_OUTPUT 

      - name: Output stripped body
        id: substitution
        # Remove previous release comment from PR body
        # using bash string substitution (https://linuxhandbook.com/replace-string-bash/)
        run: |
          start_marker="<!--release-comment-hidden-marker-start-->"
          end_marker="<!--release-comment-hidden-marker-end-->"

          prev_body=$(jq '.pull_request.body' $GITHUB_EVENT_PATH)

          new_body=${prev_body/$start_marker*$end_marker}

          echo "stripped_body=$new_body" >> $GITHUB_OUTPUT
          echo "start_marker=$start_marker" >> $GITHUB_OUTPUT 
          echo "end_marker=$end_marker" >> $GITHUB_OUTPUT 

      - uses: secureframe/pr-update-action@v3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          head-branch-regex: 'j4-[0-9]*-.*'
          base-branch-regex: 'master'
          body-template: |
            ${{ fromJSON(steps.substitution.outputs.stripped_body) }}
            ${{ steps.substitution.outputs.start_marker }}

            ### :label: This pull-request will create release `${{ needs.tag-version.outputs.new-tag-raw }}`
            
            :information_source: Previous version : `${{ needs.tag-version.outputs.previous-tag }}`
            
            :point_right: Go to the [**latest workflow run summary**](https://github.com/Job4/job4/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}) :rocket:

            > Latest run refers to : ${{ steps.cm.outputs.message }}

            <hr/>

            <details>
              <summary><h3>Release summary :spiral_notepad:</h3></summary>

            ${{ needs.tag-version.outputs.changelog }}
            </details>

            <hr/>
            ${{ steps.substitution.outputs.end_marker }}
          body-update-action: 'replace'

  add-jira-description:
    runs-on: ubuntu-20.04
    name: 💬 Jira details
    needs:
      [
        upsert-pr-body,
      ]
    steps:
      - uses: cakeinpanic/jira-description-action@v0.3.2
        name: jira-description-action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          jira-token: ${{ secrets.JIRA_TOKEN }}
          jira-base-url: https://job4.atlassian.net
          jira-project-key: "J4"
          use: both
```

**Comment by cchanche** [comment]
Oh, and also, the `secureframe/pr-update-action` is [working with context](https://github.com/tzkhan/pr-update-action/blob/bbd4c9395df8a9c4ef075b8b7fe29f2ca76cdca9/index.js#L109)

**Comment by cakeinpanic** [comment]
Putting those PR changing actions as 2 _steps_ of a **one jib** would work. Note 
* using `jira-description-action@v0.3.3` here, the latest version with an API call
* `jira-description-action` goes as last step

```
 update-pr-body:
    name: 💬 Release details
    runs-on: ubuntu-20.04
    needs:
      [     tag-version ]
    steps:

      - name: ✔️ Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

     - uses: secureframe/pr-update-action@v3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          head-branch-regex: 'j4-[0-9]*-.*'
          base-branch-regex: 'master'
          body-template: |
            ${{ fromJSON(steps.substitution.outputs.stripped_body) }}
            ${{ steps.substitution.outputs.start_marker }}

            ### :label: This pull-request will create release `${{ needs.tag-version.outputs.new-tag-raw }}`
            
            :information_source: Previous version : `${{ needs.tag-version.outputs.previous-tag }}`
            
            :point_right: Go to the [**latest workflow run summary**](https://github.com/Job4/job4/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}) :rocket:

            > Latest run refers to : ${{ steps.cm.outputs.message }}

            <hr/>

            <details>
              <summary><h3>Release summary :spiral_notepad:</h3></summary>

            ${{ needs.tag-version.outputs.changelog }}
            </details>

            <hr/>
            ${{ steps.substitution.outputs.end_marker }}
          body-update-action: 'replace'


     - uses: cakeinpanic/jira-description-action@v0.3.3
        name: jira-description-action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          jira-token: ${{ secrets.JIRA_TOKEN }}
          jira-base-url: https://job4.atlassian.net
          jira-project-key: "J4"
          use: both

**Comment by cchanche** [comment]
Can confirm, this solution works works fine, thank you !

**Pull request closed without merging**
